[package]
name = "rbfrt"
version = "0.1.11"
authors = ["Steffen Lindner", "Fabian Ihle", "Etienne Zink"]
edition = "2021"
license = "Apache-2.0"
description = "Rust library for interaction with Intel Tofino(TM) BFRT switch interface."
publish = true
repository = "https://github.com/uni-tue-kn/rbfrt"

[dependencies]
tonic = "0.14.6"
prost = "0.14.4"
prost-types = "0.14.4"
tonic-prost = "0.14.6"
tokio = { version = "1.52.3", features = ["rt-multi-thread"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
strum = "0.28.0"
strum_macros = { version = "0.28.0", features = [] }
log = "0.4.33"
tokio-stream = "0.1.18"
async-stream = "0.3.6"
crossbeam-channel = "0.5.16"
prettytable-rs = "^0.10.0"
futures-core = "0.3.32"
# Thrift support
thrift = { version = "0.23.0", optional = true }

[build-dependencies]
tonic-prost-build = "0.14.6"
prost-build = "0.14.4"

[features]
default = []
thrift-support = ["thrift"]
