// Autogenerated by Thrift Compiler (0.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

pub type pp_dev_t = i32;

pub type pp_pipe_t = i32;

pub type pp_bf_status_t = i32;

pub type pp_bf_dev_id_t = i32;

pub type pp_port_t = i32;

//
// InvalidPpOperation
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct InvalidPpOperation {
  pub code: Option<i32>,
}

impl InvalidPpOperation {
  pub fn new<F1>(code: F1) -> InvalidPpOperation where F1: Into<Option<i32>> {
    InvalidPpOperation {
      code: code.into(),
    }
  }
}

impl TSerializable for InvalidPpOperation {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<InvalidPpOperation> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = InvalidPpOperation {
      code: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("InvalidPpOperation");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.code {
      o_prot.write_field_begin(&TFieldIdentifier::new("code", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

impl Error for InvalidPpOperation {}

impl From<InvalidPpOperation> for thrift::Error {
  fn from(e: InvalidPpOperation) -> Self {
    thrift::Error::User(Box::new(e))
  }
}

impl Display for InvalidPpOperation {
  fn fmt(&self, f: &mut Formatter) -> fmt::Result {
    write!(f, "remote service threw InvalidPpOperation")
  }
}

//
// PpBfIbpDropCntrs
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PpBfIbpDropCntrs {
  pub total_pkts_drop: Option<i64>,
  pub total_pkts_disc: Option<i64>,
  pub total_recirc_pkt_disc: Option<i64>,
  pub total_prsr_pkt_disc: Option<i64>,
}

impl PpBfIbpDropCntrs {
  pub fn new<F1, F2, F3, F4>(total_pkts_drop: F1, total_pkts_disc: F2, total_recirc_pkt_disc: F3, total_prsr_pkt_disc: F4) -> PpBfIbpDropCntrs where F1: Into<Option<i64>>, F2: Into<Option<i64>>, F3: Into<Option<i64>>, F4: Into<Option<i64>> {
    PpBfIbpDropCntrs {
      total_pkts_drop: total_pkts_drop.into(),
      total_pkts_disc: total_pkts_disc.into(),
      total_recirc_pkt_disc: total_recirc_pkt_disc.into(),
      total_prsr_pkt_disc: total_prsr_pkt_disc.into(),
    }
  }
}

impl TSerializable for PpBfIbpDropCntrs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PpBfIbpDropCntrs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    let mut f_2: Option<i64> = Some(0);
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<i64> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PpBfIbpDropCntrs {
      total_pkts_drop: f_1,
      total_pkts_disc: f_2,
      total_recirc_pkt_disc: f_3,
      total_prsr_pkt_disc: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_bf_ibp_drop_cntrs");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.total_pkts_drop {
      o_prot.write_field_begin(&TFieldIdentifier::new("total_pkts_drop", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.total_pkts_disc {
      o_prot.write_field_begin(&TFieldIdentifier::new("total_pkts_disc", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.total_recirc_pkt_disc {
      o_prot.write_field_begin(&TFieldIdentifier::new("total_recirc_pkt_disc", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.total_prsr_pkt_disc {
      o_prot.write_field_begin(&TFieldIdentifier::new("total_prsr_pkt_disc", TType::I64, 4))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PpBfIprsrDropCntrs
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PpBfIprsrDropCntrs {
  pub fcs_err_count: Option<i64>,
  pub csum_err_count: Option<i64>,
  pub tcam_parity_err_count: Option<i64>,
  pub total_pkts_drop: Option<i64>,
}

impl PpBfIprsrDropCntrs {
  pub fn new<F1, F2, F3, F4>(fcs_err_count: F1, csum_err_count: F2, tcam_parity_err_count: F3, total_pkts_drop: F4) -> PpBfIprsrDropCntrs where F1: Into<Option<i64>>, F2: Into<Option<i64>>, F3: Into<Option<i64>>, F4: Into<Option<i64>> {
    PpBfIprsrDropCntrs {
      fcs_err_count: fcs_err_count.into(),
      csum_err_count: csum_err_count.into(),
      tcam_parity_err_count: tcam_parity_err_count.into(),
      total_pkts_drop: total_pkts_drop.into(),
    }
  }
}

impl TSerializable for PpBfIprsrDropCntrs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PpBfIprsrDropCntrs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    let mut f_2: Option<i64> = Some(0);
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<i64> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PpBfIprsrDropCntrs {
      fcs_err_count: f_1,
      csum_err_count: f_2,
      tcam_parity_err_count: f_3,
      total_pkts_drop: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_bf_iprsr_drop_cntrs");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.fcs_err_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("fcs_err_count", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.csum_err_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("csum_err_count", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.tcam_parity_err_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("tcam_parity_err_count", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.total_pkts_drop {
      o_prot.write_field_begin(&TFieldIdentifier::new("total_pkts_drop", TType::I64, 4))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PpBfIdprsrDropCntrs
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PpBfIdprsrDropCntrs {
  pub pkts_disc: Option<i64>,
  pub pkts_disc_at_tm: Option<i64>,
  pub err_pkts_to_tm: Option<i64>,
  pub err_pkts_to_ictm: Option<i64>,
  pub crc_err: Option<Vec<i64>>,
}

impl PpBfIdprsrDropCntrs {
  pub fn new<F1, F2, F3, F4, F5>(pkts_disc: F1, pkts_disc_at_tm: F2, err_pkts_to_tm: F3, err_pkts_to_ictm: F4, crc_err: F5) -> PpBfIdprsrDropCntrs where F1: Into<Option<i64>>, F2: Into<Option<i64>>, F3: Into<Option<i64>>, F4: Into<Option<i64>>, F5: Into<Option<Vec<i64>>> {
    PpBfIdprsrDropCntrs {
      pkts_disc: pkts_disc.into(),
      pkts_disc_at_tm: pkts_disc_at_tm.into(),
      err_pkts_to_tm: err_pkts_to_tm.into(),
      err_pkts_to_ictm: err_pkts_to_ictm.into(),
      crc_err: crc_err.into(),
    }
  }
}

impl TSerializable for PpBfIdprsrDropCntrs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PpBfIdprsrDropCntrs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    let mut f_2: Option<i64> = Some(0);
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<i64> = Some(0);
    let mut f_5: Option<Vec<i64>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        5 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<i64> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_0 = i_prot.read_i64()?;
            val.push(list_elem_0);
          }
          i_prot.read_list_end()?;
          f_5 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PpBfIdprsrDropCntrs {
      pkts_disc: f_1,
      pkts_disc_at_tm: f_2,
      err_pkts_to_tm: f_3,
      err_pkts_to_ictm: f_4,
      crc_err: f_5,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_bf_idprsr_drop_cntrs");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.pkts_disc {
      o_prot.write_field_begin(&TFieldIdentifier::new("pkts_disc", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.pkts_disc_at_tm {
      o_prot.write_field_begin(&TFieldIdentifier::new("pkts_disc_at_tm", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.err_pkts_to_tm {
      o_prot.write_field_begin(&TFieldIdentifier::new("err_pkts_to_tm", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.err_pkts_to_ictm {
      o_prot.write_field_begin(&TFieldIdentifier::new("err_pkts_to_ictm", TType::I64, 4))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.crc_err {
      o_prot.write_field_begin(&TFieldIdentifier::new("crc_err", TType::List, 5))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::I64, fld_var.len() as i32))?;
      for e in fld_var {
        o_prot.write_i64(*e)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PpBfEprsrDropCntrs
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PpBfEprsrDropCntrs {
  pub fcs_err_count: Option<i64>,
  pub csum_err_count: Option<i64>,
  pub tcam_parity_err_count: Option<i64>,
  pub total_pkts_drop: Option<i64>,
}

impl PpBfEprsrDropCntrs {
  pub fn new<F1, F2, F3, F4>(fcs_err_count: F1, csum_err_count: F2, tcam_parity_err_count: F3, total_pkts_drop: F4) -> PpBfEprsrDropCntrs where F1: Into<Option<i64>>, F2: Into<Option<i64>>, F3: Into<Option<i64>>, F4: Into<Option<i64>> {
    PpBfEprsrDropCntrs {
      fcs_err_count: fcs_err_count.into(),
      csum_err_count: csum_err_count.into(),
      tcam_parity_err_count: tcam_parity_err_count.into(),
      total_pkts_drop: total_pkts_drop.into(),
    }
  }
}

impl TSerializable for PpBfEprsrDropCntrs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PpBfEprsrDropCntrs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    let mut f_2: Option<i64> = Some(0);
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<i64> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i64()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PpBfEprsrDropCntrs {
      fcs_err_count: f_1,
      csum_err_count: f_2,
      tcam_parity_err_count: f_3,
      total_pkts_drop: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_bf_eprsr_drop_cntrs");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.fcs_err_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("fcs_err_count", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.csum_err_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("csum_err_count", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.tcam_parity_err_count {
      o_prot.write_field_begin(&TFieldIdentifier::new("tcam_parity_err_count", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.total_pkts_drop {
      o_prot.write_field_begin(&TFieldIdentifier::new("total_pkts_drop", TType::I64, 4))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PpBfEdprsrDropCntrs
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct PpBfEdprsrDropCntrs {
  pub pkts_disc: Option<i64>,
  pub err_pkts_to_ebuf: Option<i64>,
  pub err_pkts_to_ectm: Option<i64>,
  pub crc_err: Option<Vec<i64>>,
}

impl PpBfEdprsrDropCntrs {
  pub fn new<F1, F2, F3, F4>(pkts_disc: F1, err_pkts_to_ebuf: F2, err_pkts_to_ectm: F3, crc_err: F4) -> PpBfEdprsrDropCntrs where F1: Into<Option<i64>>, F2: Into<Option<i64>>, F3: Into<Option<i64>>, F4: Into<Option<Vec<i64>>> {
    PpBfEdprsrDropCntrs {
      pkts_disc: pkts_disc.into(),
      err_pkts_to_ebuf: err_pkts_to_ebuf.into(),
      err_pkts_to_ectm: err_pkts_to_ectm.into(),
      crc_err: crc_err.into(),
    }
  }
}

impl TSerializable for PpBfEdprsrDropCntrs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PpBfEdprsrDropCntrs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i64> = Some(0);
    let mut f_2: Option<i64> = Some(0);
    let mut f_3: Option<i64> = Some(0);
    let mut f_4: Option<Vec<i64>> = Some(Vec::new());
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i64()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i64()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i64()?;
          f_3 = Some(val);
        },
        4 => {
          let list_ident = i_prot.read_list_begin()?;
          let mut val: Vec<i64> = Vec::with_capacity(list_ident.size as usize);
          for _ in 0..list_ident.size {
            let list_elem_1 = i_prot.read_i64()?;
            val.push(list_elem_1);
          }
          i_prot.read_list_end()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PpBfEdprsrDropCntrs {
      pkts_disc: f_1,
      err_pkts_to_ebuf: f_2,
      err_pkts_to_ectm: f_3,
      crc_err: f_4,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_bf_edprsr_drop_cntrs");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.pkts_disc {
      o_prot.write_field_begin(&TFieldIdentifier::new("pkts_disc", TType::I64, 1))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.err_pkts_to_ebuf {
      o_prot.write_field_begin(&TFieldIdentifier::new("err_pkts_to_ebuf", TType::I64, 2))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(fld_var) = self.err_pkts_to_ectm {
      o_prot.write_field_begin(&TFieldIdentifier::new("err_pkts_to_ectm", TType::I64, 3))?;
      o_prot.write_i64(fld_var)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.crc_err {
      o_prot.write_field_begin(&TFieldIdentifier::new("crc_err", TType::List, 4))?;
      o_prot.write_list_begin(&TListIdentifier::new(TType::I64, fld_var.len() as i32))?;
      for e in fld_var {
        o_prot.write_i64(*e)?;
      }
      o_prot.write_list_end()?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// pipemgr_api service client
//

pub trait TPipemgrApiSyncClient {
  fn pp_ibp_drop_cntr_get(&mut self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfIbpDropCntrs>;
  fn pp_iprsr_drop_cntr_get(&mut self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfIprsrDropCntrs>;
  fn pp_idprsr_drop_cntr_get(&mut self, dev: pp_dev_t, pipe: pp_pipe_t) -> thrift::Result<PpBfIdprsrDropCntrs>;
  fn pp_eprsr_drop_cntr_get(&mut self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfEprsrDropCntrs>;
  fn pp_edprsr_drop_cntr_get(&mut self, dev: pp_dev_t, pipe: pp_pipe_t) -> thrift::Result<PpBfEdprsrDropCntrs>;
}

pub trait TPipemgrApiSyncClientMarker {}

pub struct PipemgrApiSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  _i_prot: IP,
  _o_prot: OP,
  _sequence_number: i32,
}

impl <IP, OP> PipemgrApiSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  pub fn new(input_protocol: IP, output_protocol: OP) -> PipemgrApiSyncClient<IP, OP> {
    PipemgrApiSyncClient { _i_prot: input_protocol, _o_prot: output_protocol, _sequence_number: 0 }
  }
}

impl <IP, OP> TThriftClient for PipemgrApiSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  fn i_prot_mut(&mut self) -> &mut dyn TInputProtocol { &mut self._i_prot }
  fn o_prot_mut(&mut self) -> &mut dyn TOutputProtocol { &mut self._o_prot }
  fn sequence_number(&self) -> i32 { self._sequence_number }
  fn increment_sequence_number(&mut self) -> i32 { self._sequence_number += 1; self._sequence_number }
}

impl <IP, OP> TPipemgrApiSyncClientMarker for PipemgrApiSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {}

impl <C: TThriftClient + TPipemgrApiSyncClientMarker> TPipemgrApiSyncClient for C {
  fn pp_ibp_drop_cntr_get(&mut self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfIbpDropCntrs> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("pp_ibp_drop_cntr_get", TMessageType::Call, self.sequence_number());
        let call_args = PipemgrApiPpIbpDropCntrGetArgs { dev, port };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("pp_ibp_drop_cntr_get", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = PipemgrApiPpIbpDropCntrGetResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn pp_iprsr_drop_cntr_get(&mut self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfIprsrDropCntrs> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("pp_iprsr_drop_cntr_get", TMessageType::Call, self.sequence_number());
        let call_args = PipemgrApiPpIprsrDropCntrGetArgs { dev, port };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("pp_iprsr_drop_cntr_get", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = PipemgrApiPpIprsrDropCntrGetResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn pp_idprsr_drop_cntr_get(&mut self, dev: pp_dev_t, pipe: pp_pipe_t) -> thrift::Result<PpBfIdprsrDropCntrs> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("pp_idprsr_drop_cntr_get", TMessageType::Call, self.sequence_number());
        let call_args = PipemgrApiPpIdprsrDropCntrGetArgs { dev, pipe };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("pp_idprsr_drop_cntr_get", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = PipemgrApiPpIdprsrDropCntrGetResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn pp_eprsr_drop_cntr_get(&mut self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfEprsrDropCntrs> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("pp_eprsr_drop_cntr_get", TMessageType::Call, self.sequence_number());
        let call_args = PipemgrApiPpEprsrDropCntrGetArgs { dev, port };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("pp_eprsr_drop_cntr_get", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = PipemgrApiPpEprsrDropCntrGetResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
  fn pp_edprsr_drop_cntr_get(&mut self, dev: pp_dev_t, pipe: pp_pipe_t) -> thrift::Result<PpBfEdprsrDropCntrs> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("pp_edprsr_drop_cntr_get", TMessageType::Call, self.sequence_number());
        let call_args = PipemgrApiPpEdprsrDropCntrGetArgs { dev, pipe };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("pp_edprsr_drop_cntr_get", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = PipemgrApiPpEdprsrDropCntrGetResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
}

//
// pipemgr_api service processor
//

pub trait PipemgrApiSyncHandler {
  fn handle_pp_ibp_drop_cntr_get(&self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfIbpDropCntrs>;
  fn handle_pp_iprsr_drop_cntr_get(&self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfIprsrDropCntrs>;
  fn handle_pp_idprsr_drop_cntr_get(&self, dev: pp_dev_t, pipe: pp_pipe_t) -> thrift::Result<PpBfIdprsrDropCntrs>;
  fn handle_pp_eprsr_drop_cntr_get(&self, dev: pp_dev_t, port: pp_port_t) -> thrift::Result<PpBfEprsrDropCntrs>;
  fn handle_pp_edprsr_drop_cntr_get(&self, dev: pp_dev_t, pipe: pp_pipe_t) -> thrift::Result<PpBfEdprsrDropCntrs>;
}

pub struct PipemgrApiSyncProcessor<H: PipemgrApiSyncHandler> {
  handler: H,
}

impl <H: PipemgrApiSyncHandler> PipemgrApiSyncProcessor<H> {
  pub fn new(handler: H) -> PipemgrApiSyncProcessor<H> {
    PipemgrApiSyncProcessor {
      handler,
    }
  }
  fn process_pp_ibp_drop_cntr_get(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TPipemgrApiProcessFunctions::process_pp_ibp_drop_cntr_get(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_pp_iprsr_drop_cntr_get(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TPipemgrApiProcessFunctions::process_pp_iprsr_drop_cntr_get(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_pp_idprsr_drop_cntr_get(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TPipemgrApiProcessFunctions::process_pp_idprsr_drop_cntr_get(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_pp_eprsr_drop_cntr_get(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TPipemgrApiProcessFunctions::process_pp_eprsr_drop_cntr_get(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
  fn process_pp_edprsr_drop_cntr_get(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TPipemgrApiProcessFunctions::process_pp_edprsr_drop_cntr_get(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
}

pub struct TPipemgrApiProcessFunctions;

impl TPipemgrApiProcessFunctions {
  pub fn process_pp_ibp_drop_cntr_get<H: PipemgrApiSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = PipemgrApiPpIbpDropCntrGetArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_pp_ibp_drop_cntr_get(args.dev, args.port) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("pp_ibp_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = PipemgrApiPpIbpDropCntrGetResult { result_value: Some(handler_return), ouch: None };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::User(usr_err) => {
            if usr_err.downcast_ref::<InvalidPpOperation>().is_some() {
              let err = usr_err.downcast::<InvalidPpOperation>().expect("downcast already checked");
              let ret_err = PipemgrApiPpIbpDropCntrGetResult{ result_value: None, ouch: Some(*err) };
              let message_ident = TMessageIdentifier::new("pp_ibp_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              ret_err.write_to_out_protocol(o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            } else {
              let ret_err = {
                ApplicationError::new(
                  ApplicationErrorKind::Unknown,
                  usr_err.to_string()
                )
              };
              let message_ident = TMessageIdentifier::new("pp_ibp_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            }
          },
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("pp_ibp_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("pp_ibp_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_pp_iprsr_drop_cntr_get<H: PipemgrApiSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = PipemgrApiPpIprsrDropCntrGetArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_pp_iprsr_drop_cntr_get(args.dev, args.port) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("pp_iprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = PipemgrApiPpIprsrDropCntrGetResult { result_value: Some(handler_return), ouch: None };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::User(usr_err) => {
            if usr_err.downcast_ref::<InvalidPpOperation>().is_some() {
              let err = usr_err.downcast::<InvalidPpOperation>().expect("downcast already checked");
              let ret_err = PipemgrApiPpIprsrDropCntrGetResult{ result_value: None, ouch: Some(*err) };
              let message_ident = TMessageIdentifier::new("pp_iprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              ret_err.write_to_out_protocol(o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            } else {
              let ret_err = {
                ApplicationError::new(
                  ApplicationErrorKind::Unknown,
                  usr_err.to_string()
                )
              };
              let message_ident = TMessageIdentifier::new("pp_iprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            }
          },
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("pp_iprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("pp_iprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_pp_idprsr_drop_cntr_get<H: PipemgrApiSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = PipemgrApiPpIdprsrDropCntrGetArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_pp_idprsr_drop_cntr_get(args.dev, args.pipe) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("pp_idprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = PipemgrApiPpIdprsrDropCntrGetResult { result_value: Some(handler_return), ouch: None };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::User(usr_err) => {
            if usr_err.downcast_ref::<InvalidPpOperation>().is_some() {
              let err = usr_err.downcast::<InvalidPpOperation>().expect("downcast already checked");
              let ret_err = PipemgrApiPpIdprsrDropCntrGetResult{ result_value: None, ouch: Some(*err) };
              let message_ident = TMessageIdentifier::new("pp_idprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              ret_err.write_to_out_protocol(o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            } else {
              let ret_err = {
                ApplicationError::new(
                  ApplicationErrorKind::Unknown,
                  usr_err.to_string()
                )
              };
              let message_ident = TMessageIdentifier::new("pp_idprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            }
          },
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("pp_idprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("pp_idprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_pp_eprsr_drop_cntr_get<H: PipemgrApiSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = PipemgrApiPpEprsrDropCntrGetArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_pp_eprsr_drop_cntr_get(args.dev, args.port) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("pp_eprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = PipemgrApiPpEprsrDropCntrGetResult { result_value: Some(handler_return), ouch: None };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::User(usr_err) => {
            if usr_err.downcast_ref::<InvalidPpOperation>().is_some() {
              let err = usr_err.downcast::<InvalidPpOperation>().expect("downcast already checked");
              let ret_err = PipemgrApiPpEprsrDropCntrGetResult{ result_value: None, ouch: Some(*err) };
              let message_ident = TMessageIdentifier::new("pp_eprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              ret_err.write_to_out_protocol(o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            } else {
              let ret_err = {
                ApplicationError::new(
                  ApplicationErrorKind::Unknown,
                  usr_err.to_string()
                )
              };
              let message_ident = TMessageIdentifier::new("pp_eprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            }
          },
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("pp_eprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("pp_eprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
  pub fn process_pp_edprsr_drop_cntr_get<H: PipemgrApiSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = PipemgrApiPpEdprsrDropCntrGetArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_pp_edprsr_drop_cntr_get(args.dev, args.pipe) {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("pp_edprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = PipemgrApiPpEdprsrDropCntrGetResult { result_value: Some(handler_return), ouch: None };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::User(usr_err) => {
            if usr_err.downcast_ref::<InvalidPpOperation>().is_some() {
              let err = usr_err.downcast::<InvalidPpOperation>().expect("downcast already checked");
              let ret_err = PipemgrApiPpEdprsrDropCntrGetResult{ result_value: None, ouch: Some(*err) };
              let message_ident = TMessageIdentifier::new("pp_edprsr_drop_cntr_get", TMessageType::Reply, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              ret_err.write_to_out_protocol(o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            } else {
              let ret_err = {
                ApplicationError::new(
                  ApplicationErrorKind::Unknown,
                  usr_err.to_string()
                )
              };
              let message_ident = TMessageIdentifier::new("pp_edprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            }
          },
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("pp_edprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("pp_edprsr_drop_cntr_get", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
}

impl <H: PipemgrApiSyncHandler> TProcessor for PipemgrApiSyncProcessor<H> {
  fn process(&self, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let message_ident = i_prot.read_message_begin()?;
    let res = match &*message_ident.name {
      "pp_ibp_drop_cntr_get" => {
        self.process_pp_ibp_drop_cntr_get(message_ident.sequence_number, i_prot, o_prot)
      },
      "pp_iprsr_drop_cntr_get" => {
        self.process_pp_iprsr_drop_cntr_get(message_ident.sequence_number, i_prot, o_prot)
      },
      "pp_idprsr_drop_cntr_get" => {
        self.process_pp_idprsr_drop_cntr_get(message_ident.sequence_number, i_prot, o_prot)
      },
      "pp_eprsr_drop_cntr_get" => {
        self.process_pp_eprsr_drop_cntr_get(message_ident.sequence_number, i_prot, o_prot)
      },
      "pp_edprsr_drop_cntr_get" => {
        self.process_pp_edprsr_drop_cntr_get(message_ident.sequence_number, i_prot, o_prot)
      },
      method => {
        Err(
          thrift::Error::Application(
            ApplicationError::new(
              ApplicationErrorKind::UnknownMethod,
              format!("unknown method {}", method)
            )
          )
        )
      },
    };
    thrift::server::handle_process_result(&message_ident, res, o_prot)
  }
}

//
// PipemgrApiPpIbpDropCntrGetArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpIbpDropCntrGetArgs {
  dev: pp_dev_t,
  port: pp_port_t,
}

impl PipemgrApiPpIbpDropCntrGetArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpIbpDropCntrGetArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<pp_dev_t> = None;
    let mut f_2: Option<pp_port_t> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PipemgrApiPpIbpDropCntrGetArgs.dev", &f_1)?;
    verify_required_field_exists("PipemgrApiPpIbpDropCntrGetArgs.port", &f_2)?;
    let ret = PipemgrApiPpIbpDropCntrGetArgs {
      dev: f_1.expect("auto-generated code should have checked for presence of required fields"),
      port: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_ibp_drop_cntr_get_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev", TType::I32, 1))?;
    o_prot.write_i32(self.dev)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("port", TType::I32, 2))?;
    o_prot.write_i32(self.port)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpIbpDropCntrGetResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpIbpDropCntrGetResult {
  result_value: Option<PpBfIbpDropCntrs>,
  ouch: Option<InvalidPpOperation>,
}

impl PipemgrApiPpIbpDropCntrGetResult {
  fn ok_or(self) -> thrift::Result<PpBfIbpDropCntrs> {
    if self.ouch.is_some() {
      Err(thrift::Error::User(Box::new(self.ouch.unwrap())))
    } else if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for PipemgrApiPpIbpDropCntrGet"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpIbpDropCntrGetResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<PpBfIbpDropCntrs> = None;
    let mut f_1: Option<InvalidPpOperation> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = PpBfIbpDropCntrs::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        1 => {
          let val = InvalidPpOperation::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PipemgrApiPpIbpDropCntrGetResult {
      result_value: f_0,
      ouch: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PipemgrApiPpIbpDropCntrGetResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.ouch {
      o_prot.write_field_begin(&TFieldIdentifier::new("ouch", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpIprsrDropCntrGetArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpIprsrDropCntrGetArgs {
  dev: pp_dev_t,
  port: pp_port_t,
}

impl PipemgrApiPpIprsrDropCntrGetArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpIprsrDropCntrGetArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<pp_dev_t> = None;
    let mut f_2: Option<pp_port_t> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PipemgrApiPpIprsrDropCntrGetArgs.dev", &f_1)?;
    verify_required_field_exists("PipemgrApiPpIprsrDropCntrGetArgs.port", &f_2)?;
    let ret = PipemgrApiPpIprsrDropCntrGetArgs {
      dev: f_1.expect("auto-generated code should have checked for presence of required fields"),
      port: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_iprsr_drop_cntr_get_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev", TType::I32, 1))?;
    o_prot.write_i32(self.dev)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("port", TType::I32, 2))?;
    o_prot.write_i32(self.port)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpIprsrDropCntrGetResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpIprsrDropCntrGetResult {
  result_value: Option<PpBfIprsrDropCntrs>,
  ouch: Option<InvalidPpOperation>,
}

impl PipemgrApiPpIprsrDropCntrGetResult {
  fn ok_or(self) -> thrift::Result<PpBfIprsrDropCntrs> {
    if self.ouch.is_some() {
      Err(thrift::Error::User(Box::new(self.ouch.unwrap())))
    } else if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for PipemgrApiPpIprsrDropCntrGet"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpIprsrDropCntrGetResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<PpBfIprsrDropCntrs> = None;
    let mut f_1: Option<InvalidPpOperation> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = PpBfIprsrDropCntrs::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        1 => {
          let val = InvalidPpOperation::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PipemgrApiPpIprsrDropCntrGetResult {
      result_value: f_0,
      ouch: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PipemgrApiPpIprsrDropCntrGetResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.ouch {
      o_prot.write_field_begin(&TFieldIdentifier::new("ouch", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpIdprsrDropCntrGetArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpIdprsrDropCntrGetArgs {
  dev: pp_dev_t,
  pipe: pp_pipe_t,
}

impl PipemgrApiPpIdprsrDropCntrGetArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpIdprsrDropCntrGetArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<pp_dev_t> = None;
    let mut f_2: Option<pp_pipe_t> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PipemgrApiPpIdprsrDropCntrGetArgs.dev", &f_1)?;
    verify_required_field_exists("PipemgrApiPpIdprsrDropCntrGetArgs.pipe", &f_2)?;
    let ret = PipemgrApiPpIdprsrDropCntrGetArgs {
      dev: f_1.expect("auto-generated code should have checked for presence of required fields"),
      pipe: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_idprsr_drop_cntr_get_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev", TType::I32, 1))?;
    o_prot.write_i32(self.dev)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("pipe", TType::I32, 2))?;
    o_prot.write_i32(self.pipe)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpIdprsrDropCntrGetResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpIdprsrDropCntrGetResult {
  result_value: Option<PpBfIdprsrDropCntrs>,
  ouch: Option<InvalidPpOperation>,
}

impl PipemgrApiPpIdprsrDropCntrGetResult {
  fn ok_or(self) -> thrift::Result<PpBfIdprsrDropCntrs> {
    if self.ouch.is_some() {
      Err(thrift::Error::User(Box::new(self.ouch.unwrap())))
    } else if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for PipemgrApiPpIdprsrDropCntrGet"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpIdprsrDropCntrGetResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<PpBfIdprsrDropCntrs> = None;
    let mut f_1: Option<InvalidPpOperation> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = PpBfIdprsrDropCntrs::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        1 => {
          let val = InvalidPpOperation::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PipemgrApiPpIdprsrDropCntrGetResult {
      result_value: f_0,
      ouch: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PipemgrApiPpIdprsrDropCntrGetResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.ouch {
      o_prot.write_field_begin(&TFieldIdentifier::new("ouch", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpEprsrDropCntrGetArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpEprsrDropCntrGetArgs {
  dev: pp_dev_t,
  port: pp_port_t,
}

impl PipemgrApiPpEprsrDropCntrGetArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpEprsrDropCntrGetArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<pp_dev_t> = None;
    let mut f_2: Option<pp_port_t> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PipemgrApiPpEprsrDropCntrGetArgs.dev", &f_1)?;
    verify_required_field_exists("PipemgrApiPpEprsrDropCntrGetArgs.port", &f_2)?;
    let ret = PipemgrApiPpEprsrDropCntrGetArgs {
      dev: f_1.expect("auto-generated code should have checked for presence of required fields"),
      port: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_eprsr_drop_cntr_get_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev", TType::I32, 1))?;
    o_prot.write_i32(self.dev)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("port", TType::I32, 2))?;
    o_prot.write_i32(self.port)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpEprsrDropCntrGetResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpEprsrDropCntrGetResult {
  result_value: Option<PpBfEprsrDropCntrs>,
  ouch: Option<InvalidPpOperation>,
}

impl PipemgrApiPpEprsrDropCntrGetResult {
  fn ok_or(self) -> thrift::Result<PpBfEprsrDropCntrs> {
    if self.ouch.is_some() {
      Err(thrift::Error::User(Box::new(self.ouch.unwrap())))
    } else if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for PipemgrApiPpEprsrDropCntrGet"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpEprsrDropCntrGetResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<PpBfEprsrDropCntrs> = None;
    let mut f_1: Option<InvalidPpOperation> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = PpBfEprsrDropCntrs::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        1 => {
          let val = InvalidPpOperation::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PipemgrApiPpEprsrDropCntrGetResult {
      result_value: f_0,
      ouch: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PipemgrApiPpEprsrDropCntrGetResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.ouch {
      o_prot.write_field_begin(&TFieldIdentifier::new("ouch", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpEdprsrDropCntrGetArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpEdprsrDropCntrGetArgs {
  dev: pp_dev_t,
  pipe: pp_pipe_t,
}

impl PipemgrApiPpEdprsrDropCntrGetArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpEdprsrDropCntrGetArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<pp_dev_t> = None;
    let mut f_2: Option<pp_pipe_t> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PipemgrApiPpEdprsrDropCntrGetArgs.dev", &f_1)?;
    verify_required_field_exists("PipemgrApiPpEdprsrDropCntrGetArgs.pipe", &f_2)?;
    let ret = PipemgrApiPpEdprsrDropCntrGetArgs {
      dev: f_1.expect("auto-generated code should have checked for presence of required fields"),
      pipe: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("pp_edprsr_drop_cntr_get_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev", TType::I32, 1))?;
    o_prot.write_i32(self.dev)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("pipe", TType::I32, 2))?;
    o_prot.write_i32(self.pipe)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PipemgrApiPpEdprsrDropCntrGetResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PipemgrApiPpEdprsrDropCntrGetResult {
  result_value: Option<PpBfEdprsrDropCntrs>,
  ouch: Option<InvalidPpOperation>,
}

impl PipemgrApiPpEdprsrDropCntrGetResult {
  fn ok_or(self) -> thrift::Result<PpBfEdprsrDropCntrs> {
    if self.ouch.is_some() {
      Err(thrift::Error::User(Box::new(self.ouch.unwrap())))
    } else if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for PipemgrApiPpEdprsrDropCntrGet"
          )
        )
      )
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PipemgrApiPpEdprsrDropCntrGetResult> {
    i_prot.read_struct_begin()?;
    let mut f_0: Option<PpBfEdprsrDropCntrs> = None;
    let mut f_1: Option<InvalidPpOperation> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = PpBfEdprsrDropCntrs::read_from_in_protocol(i_prot)?;
          f_0 = Some(val);
        },
        1 => {
          let val = InvalidPpOperation::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PipemgrApiPpEdprsrDropCntrGetResult {
      result_value: f_0,
      ouch: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PipemgrApiPpEdprsrDropCntrGetResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::Struct, 0))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    if let Some(ref fld_var) = self.ouch {
      o_prot.write_field_begin(&TFieldIdentifier::new("ouch", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

