// Autogenerated by Thrift Compiler (0.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

use crate::res;

//
// InvalidPortMgrOperation
//

#[derive(Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct InvalidPortMgrOperation {
  pub code: Option<i32>,
}

impl InvalidPortMgrOperation {
  pub fn new<F1>(code: F1) -> InvalidPortMgrOperation where F1: Into<Option<i32>> {
    InvalidPortMgrOperation {
      code: code.into(),
    }
  }
}

impl TSerializable for InvalidPortMgrOperation {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<InvalidPortMgrOperation> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = Some(0);
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = InvalidPortMgrOperation {
      code: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("InvalidPortMgrOperation");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(fld_var) = self.code {
      o_prot.write_field_begin(&TFieldIdentifier::new("code", TType::I32, 1))?;
      o_prot.write_i32(fld_var)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

impl Error for InvalidPortMgrOperation {}

impl From<InvalidPortMgrOperation> for thrift::Error {
  fn from(e: InvalidPortMgrOperation) -> Self {
    thrift::Error::User(Box::new(e))
  }
}

impl Display for InvalidPortMgrOperation {
  fn fmt(&self, f: &mut Formatter) -> fmt::Result {
    write!(f, "remote service threw InvalidPortMgrOperation")
  }
}

//
// port_mgr service client
//

pub trait TPortMgrSyncClient {
  fn port_mgr_mtu_set(&mut self, dev_id: i32, port_id: i32, tx_mtu: i32, rx_mtu: i32) -> thrift::Result<()>;
}

pub trait TPortMgrSyncClientMarker {}

pub struct PortMgrSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  _i_prot: IP,
  _o_prot: OP,
  _sequence_number: i32,
}

impl <IP, OP> PortMgrSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  pub fn new(input_protocol: IP, output_protocol: OP) -> PortMgrSyncClient<IP, OP> {
    PortMgrSyncClient { _i_prot: input_protocol, _o_prot: output_protocol, _sequence_number: 0 }
  }
}

impl <IP, OP> TThriftClient for PortMgrSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {
  fn i_prot_mut(&mut self) -> &mut dyn TInputProtocol { &mut self._i_prot }
  fn o_prot_mut(&mut self) -> &mut dyn TOutputProtocol { &mut self._o_prot }
  fn sequence_number(&self) -> i32 { self._sequence_number }
  fn increment_sequence_number(&mut self) -> i32 { self._sequence_number += 1; self._sequence_number }
}

impl <IP, OP> TPortMgrSyncClientMarker for PortMgrSyncClient<IP, OP> where IP: TInputProtocol, OP: TOutputProtocol {}

impl <C: TThriftClient + TPortMgrSyncClientMarker> TPortMgrSyncClient for C {
  fn port_mgr_mtu_set(&mut self, dev_id: i32, port_id: i32, tx_mtu: i32, rx_mtu: i32) -> thrift::Result<()> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("port_mgr_mtu_set", TMessageType::Call, self.sequence_number());
        let call_args = PortMgrPortMgrMtuSetArgs { dev_id, port_id, tx_mtu, rx_mtu };
        self.o_prot_mut().write_message_begin(&message_ident)?;
        call_args.write_to_out_protocol(self.o_prot_mut())?;
        self.o_prot_mut().write_message_end()?;
        self.o_prot_mut().flush()
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin()?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("port_mgr_mtu_set", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut())?;
        self.i_prot_mut().read_message_end()?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = PortMgrPortMgrMtuSetResult::read_from_in_protocol(self.i_prot_mut())?;
      self.i_prot_mut().read_message_end()?;
      result.ok_or()
    }
  }
}

//
// port_mgr service processor
//

pub trait PortMgrSyncHandler {
  fn handle_port_mgr_mtu_set(&self, dev_id: i32, port_id: i32, tx_mtu: i32, rx_mtu: i32) -> thrift::Result<()>;
}

pub struct PortMgrSyncProcessor<H: PortMgrSyncHandler> {
  handler: H,
}

impl <H: PortMgrSyncHandler> PortMgrSyncProcessor<H> {
  pub fn new(handler: H) -> PortMgrSyncProcessor<H> {
    PortMgrSyncProcessor {
      handler,
    }
  }
  fn process_port_mgr_mtu_set(&self, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    TPortMgrProcessFunctions::process_port_mgr_mtu_set(&self.handler, incoming_sequence_number, i_prot, o_prot)
  }
}

pub struct TPortMgrProcessFunctions;

impl TPortMgrProcessFunctions {
  pub fn process_port_mgr_mtu_set<H: PortMgrSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let args = PortMgrPortMgrMtuSetArgs::read_from_in_protocol(i_prot)?;
    match handler.handle_port_mgr_mtu_set(args.dev_id, args.port_id, args.tx_mtu, args.rx_mtu) {
      Ok(_) => {
        let message_ident = TMessageIdentifier::new("port_mgr_mtu_set", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident)?;
        let ret = PortMgrPortMgrMtuSetResult { ouch: None };
        ret.write_to_out_protocol(o_prot)?;
        o_prot.write_message_end()?;
        o_prot.flush()
      },
      Err(e) => {
        match e {
          thrift::Error::User(usr_err) => {
            if usr_err.downcast_ref::<InvalidPortMgrOperation>().is_some() {
              let err = usr_err.downcast::<InvalidPortMgrOperation>().expect("downcast already checked");
              let ret_err = PortMgrPortMgrMtuSetResult{ ouch: Some(*err) };
              let message_ident = TMessageIdentifier::new("port_mgr_mtu_set", TMessageType::Reply, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              ret_err.write_to_out_protocol(o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            } else {
              let ret_err = {
                ApplicationError::new(
                  ApplicationErrorKind::Unknown,
                  usr_err.to_string()
                )
              };
              let message_ident = TMessageIdentifier::new("port_mgr_mtu_set", TMessageType::Exception, incoming_sequence_number);
              o_prot.write_message_begin(&message_ident)?;
              thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
              o_prot.write_message_end()?;
              o_prot.flush()
            }
          },
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("port_mgr_mtu_set", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.to_string()
              )
            };
            let message_ident = TMessageIdentifier::new("port_mgr_mtu_set", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident)?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot)?;
            o_prot.write_message_end()?;
            o_prot.flush()
          },
        }
      },
    }
  }
}

impl <H: PortMgrSyncHandler> TProcessor for PortMgrSyncProcessor<H> {
  fn process(&self, i_prot: &mut dyn TInputProtocol, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let message_ident = i_prot.read_message_begin()?;
    let res = match &*message_ident.name {
      "port_mgr_mtu_set" => {
        self.process_port_mgr_mtu_set(message_ident.sequence_number, i_prot, o_prot)
      },
      method => {
        Err(
          thrift::Error::Application(
            ApplicationError::new(
              ApplicationErrorKind::UnknownMethod,
              format!("unknown method {}", method)
            )
          )
        )
      },
    };
    thrift::server::handle_process_result(&message_ident, res, o_prot)
  }
}

//
// PortMgrPortMgrMtuSetArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PortMgrPortMgrMtuSetArgs {
  dev_id: i32,
  port_id: i32,
  tx_mtu: i32,
  rx_mtu: i32,
}

impl PortMgrPortMgrMtuSetArgs {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PortMgrPortMgrMtuSetArgs> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = None;
    let mut f_2: Option<i32> = None;
    let mut f_3: Option<i32> = None;
    let mut f_4: Option<i32> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i32()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i32()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("PortMgrPortMgrMtuSetArgs.dev_id", &f_1)?;
    verify_required_field_exists("PortMgrPortMgrMtuSetArgs.port_id", &f_2)?;
    verify_required_field_exists("PortMgrPortMgrMtuSetArgs.tx_mtu", &f_3)?;
    verify_required_field_exists("PortMgrPortMgrMtuSetArgs.rx_mtu", &f_4)?;
    let ret = PortMgrPortMgrMtuSetArgs {
      dev_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      port_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      tx_mtu: f_3.expect("auto-generated code should have checked for presence of required fields"),
      rx_mtu: f_4.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("port_mgr_mtu_set_args");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev_id", TType::I32, 1))?;
    o_prot.write_i32(self.dev_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("port_id", TType::I32, 2))?;
    o_prot.write_i32(self.port_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("tx_mtu", TType::I32, 3))?;
    o_prot.write_i32(self.tx_mtu)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("rx_mtu", TType::I32, 4))?;
    o_prot.write_i32(self.rx_mtu)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// PortMgrPortMgrMtuSetResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct PortMgrPortMgrMtuSetResult {
  ouch: Option<InvalidPortMgrOperation>,
}

impl PortMgrPortMgrMtuSetResult {
  fn ok_or(self) -> thrift::Result<()> {
    if self.ouch.is_some() {
      Err(thrift::Error::User(Box::new(self.ouch.unwrap())))
    } else {
      Ok(())
    }
  }
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<PortMgrPortMgrMtuSetResult> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<InvalidPortMgrOperation> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = InvalidPortMgrOperation::read_from_in_protocol(i_prot)?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    let ret = PortMgrPortMgrMtuSetResult {
      ouch: f_1,
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("PortMgrPortMgrMtuSetResult");
    o_prot.write_struct_begin(&struct_ident)?;
    if let Some(ref fld_var) = self.ouch {
      o_prot.write_field_begin(&TFieldIdentifier::new("ouch", TType::Struct, 1))?;
      fld_var.write_to_out_protocol(o_prot)?;
      o_prot.write_field_end()?
    }
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

