// Autogenerated by Thrift Compiler (0.19.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::vec_box, clippy::wrong_self_convention)]
#![cfg_attr(rustfmt, rustfmt_skip)]

use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::OrderedFloat;
use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TInputProtocol, TOutputProtocol, TSerializable, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TProcessor;

pub type SessionHandle_t = i32;

//
// DevTargetT
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct DevTargetT {
  pub dev_id: i32,
  pub dev_pipe_id: i16,
}

impl DevTargetT {
  pub fn new(dev_id: i32, dev_pipe_id: i16) -> DevTargetT {
    DevTargetT {
      dev_id,
      dev_pipe_id,
    }
  }
}

impl TSerializable for DevTargetT {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<DevTargetT> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = None;
    let mut f_2: Option<i16> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i16()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("DevTargetT.dev_id", &f_1)?;
    verify_required_field_exists("DevTargetT.dev_pipe_id", &f_2)?;
    let ret = DevTargetT {
      dev_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      dev_pipe_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("DevTarget_t");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev_id", TType::I32, 1))?;
    o_prot.write_i32(self.dev_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev_pipe_id", TType::I16, 2))?;
    o_prot.write_i16(self.dev_pipe_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// DevPortTargetT
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct DevPortTargetT {
  pub dev_pipe_id: i16,
  pub port_id: i16,
}

impl DevPortTargetT {
  pub fn new(dev_pipe_id: i16, port_id: i16) -> DevPortTargetT {
    DevPortTargetT {
      dev_pipe_id,
      port_id,
    }
  }
}

impl TSerializable for DevPortTargetT {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<DevPortTargetT> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i16> = None;
    let mut f_2: Option<i16> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i16()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i16()?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("DevPortTargetT.dev_pipe_id", &f_1)?;
    verify_required_field_exists("DevPortTargetT.port_id", &f_2)?;
    let ret = DevPortTargetT {
      dev_pipe_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      port_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("DevPortTarget_t");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev_pipe_id", TType::I16, 1))?;
    o_prot.write_i16(self.dev_pipe_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("port_id", TType::I16, 2))?;
    o_prot.write_i16(self.port_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

//
// DevParserTargetT
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct DevParserTargetT {
  pub dev_id: i32,
  pub gress_id: i8,
  pub dev_pipe_id: i16,
  pub parser_id: i8,
}

impl DevParserTargetT {
  pub fn new(dev_id: i32, gress_id: i8, dev_pipe_id: i16, parser_id: i8) -> DevParserTargetT {
    DevParserTargetT {
      dev_id,
      gress_id,
      dev_pipe_id,
      parser_id,
    }
  }
}

impl TSerializable for DevParserTargetT {
  fn read_from_in_protocol(i_prot: &mut dyn TInputProtocol) -> thrift::Result<DevParserTargetT> {
    i_prot.read_struct_begin()?;
    let mut f_1: Option<i32> = None;
    let mut f_2: Option<i8> = None;
    let mut f_3: Option<i16> = None;
    let mut f_4: Option<i8> = None;
    loop {
      let field_ident = i_prot.read_field_begin()?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32()?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i8()?;
          f_2 = Some(val);
        },
        3 => {
          let val = i_prot.read_i16()?;
          f_3 = Some(val);
        },
        4 => {
          let val = i_prot.read_i8()?;
          f_4 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type)?;
        },
      };
      i_prot.read_field_end()?;
    }
    i_prot.read_struct_end()?;
    verify_required_field_exists("DevParserTargetT.dev_id", &f_1)?;
    verify_required_field_exists("DevParserTargetT.gress_id", &f_2)?;
    verify_required_field_exists("DevParserTargetT.dev_pipe_id", &f_3)?;
    verify_required_field_exists("DevParserTargetT.parser_id", &f_4)?;
    let ret = DevParserTargetT {
      dev_id: f_1.expect("auto-generated code should have checked for presence of required fields"),
      gress_id: f_2.expect("auto-generated code should have checked for presence of required fields"),
      dev_pipe_id: f_3.expect("auto-generated code should have checked for presence of required fields"),
      parser_id: f_4.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  fn write_to_out_protocol(&self, o_prot: &mut dyn TOutputProtocol) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("DevParserTarget_t");
    o_prot.write_struct_begin(&struct_ident)?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev_id", TType::I32, 1))?;
    o_prot.write_i32(self.dev_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("gress_id", TType::I08, 2))?;
    o_prot.write_i8(self.gress_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("dev_pipe_id", TType::I16, 3))?;
    o_prot.write_i16(self.dev_pipe_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_begin(&TFieldIdentifier::new("parser_id", TType::I08, 4))?;
    o_prot.write_i8(self.parser_id)?;
    o_prot.write_field_end()?;
    o_prot.write_field_stop()?;
    o_prot.write_struct_end()
  }
}

