//! This module includes the code that is automaticly generated by a Protobuf compiler from the [Open Tofino](https://github.com/barefootnetworks/Open-Tofino) Protobuf definitions.

#[allow(dead_code, clippy::all)]
pub mod bfrt_proto;
#[allow(dead_code, clippy::all)]
pub mod google_protobuf;
#[allow(dead_code, clippy::all)]
pub mod google {
    pub mod rpc {
        include!("google_rpc.rs");
    }
}
#[allow(dead_code, clippy::all)]
pub mod protobuf {
    include!("google_protobuf.rs");
}
