//! This module includes the code that is automaticly generated by a Protobuf compiler from the [Open Tofino](https://github.com/barefootnetworks/Open-Tofino) Protobuf definitions.

#[allow(clippy::all)]
pub mod bfrt_proto;
pub mod google_rpc;
