name: build

on:
  push:
    branches: [ main, dev, doc ]
  pull_request:
    branches: [ main, dev, doc ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Check formatting
      run: cargo fmt --check --all
    - 
      name: Check linting
      run: cargo clippy --all-targets --all-features
    - 
      name: Build project
      run: cargo build
    - 
      name: Build documentation
      run: cargo doc
    - 
      name: Run doc tests
      run: cargo test --doc --verbose
